#  Introducción  {.unnumbered}

\- Los estudios sobre el microbioma humano se enmarcan en el ámbito de los datos de composición, ya que \<font color="blue"\> las abundancias absolutas de microorganismos no pueden obtenerse a partir de los datos de secuenciación\</font\>.

\- Cada muestra consiste en proporciones de varios microrganismos con una suma limitada a una constante. Esta simple característica hace que \<font color="blue"\> los tratamientos estadísticos tradicionales lleven a resultados erróneos y correlaciones espurias\</font\>.

## Objetivos del seminario 

\*i.- Discutiremos los \`orígenes\` de la composicionalidad en los datos del microbioma.\*

\*ii.- Mostraremos los principales \`problemas\` de utilizar los métodos estadísticos tradicionales para tratar los datos de secuenciación.\*

\*iii.- Indicaremos los reemplazos composicionales de las técnicas del \`tool kit\` de análisis de datos de microbioma.\*

\*iv.- \`CODA en acción\`: trabajaremos con un ejemplo de datos de la microbiota humana, veremos el tipo de resultados que podemos obtener.\*
